import img from '../assets/react.svg';
export const Carddata = [
    {
        id: 1,
        productName: " Nike Shoe",
        productImage: img,
        price: 499,
        oldPrice: 599,
        discountBadge: "20% OFF",
        badgeType: "hot",
        rating: 4.5,
        detailsLink: "/product/1",
        onViewDetails: () => alert("Viewing details"),
        onAddToCart: () => alert("Added to cart"),
        onFavoriteClick: (isFav) => console.log("Favorite Clicked: ", isFav),
    },
    {
        id: 2,
        productName: "Wooden Chair",
        productImage: img,
        price: 899,
        oldPrice: 1099,
        discountBadge: "18% OFF",
        badgeType: "bestSeller",
        rating: 5,
        detailsLink: "/product/2",
        onViewDetails: () => alert("Viewing details"),
        onAddToCart: () => alert("Added to cart"),
        onFavoriteClick: (isFav) => console.log("Favorite Clicked: ", isFav),
    },
    {
        id: 3,
        productName: "Watches",
        productImage: img,
        price: 699,
        oldPrice: 1099,
        discountBadge: "28% OFF",
        badgeType: "new",
        rating: 5,
        detailsLink: "/product/3",
        onViewDetails: () => alert("Viewing details"),
        onAddToCart: () => alert("Added to cart"),
        onFavoriteClick: (isFav) => console.log("Favorite Clicked: ", isFav),
    },
    {
        id: 4,
        productName: "Laptop",
        productImage: img,
        price: 800,
        oldPrice: 1000,
        discountBadge: "15% OFF",
        badgeType: "limited",
        rating: 5,
        detailsLink: "/product/4",
        onViewDetails: () => alert("Viewing details"),
        onAddToCart: () => alert("Added to cart"),
        onFavoriteClick: (isFav) => console.log("Favorite Clicked: ", isFav),
    },
];
